### ISSUE TITLE
[Bug] Basic Authentication is not being sent on the headers

### ISSUE THREAD

**Issue by vhugogarcia** [heldersepu/Swagger-Net#24]
Hello,

First, I would like to thank you for this amazing library. It is really cool and works great. However, I think I found a bug, when setting up the basic auth on the SwaggerConfig file a button appears on the UI which is correct, however even if we set the username and password correctly I always get Un-Authorized. By debugging in the Firebug console it never sends the Auth basic credentials set on the fields.

Am I missing something on the setup or is this a bug?

Thanks in advance,
Victor

**Comment by heldersepu** [comment]
Do you a sample project reproducing this issue?

**Comment by vhugogarcia** [comment]
Hello @heldersepu ,

Thanks for the faster answer. Let me create another sample project with the same logic to demo it to you. I cannot share the main project one due privacy. However, I'm happy to help by creating a quick demo sample.

I will get back to you as soon as I get it.

Thanks.

**Comment by heldersepu** [comment]
Awesome! try to keep it as simple as possible, one controller one action and only change the SwaggerConfig  with what you absolutely need.

**Comment by vhugogarcia** [comment]
Hello @heldersepu ,

I apologize for the delay. Here you have the zip file of a project using the library having the issue mentioned above.

https://www.dropbox.com/s/dm4sfo9kz5bv1vd/SwaggerDemo.zip?dl=0

Let me know if there are any questions

Thanks,
Victor

**Comment by heldersepu** [comment]
Dude that file is huge!
When you share source code (c#)  you don't need to send the packages folder or the Bin and Obj folder, that  significantly reduces the size of your project.
I'm debugging right now, let see what is causing the issue...

**Comment by heldersepu** [comment]
I added your sample project here:
https://github.com/heldersepu/csharp-proj/tree/SwaggerBasicAuthDemo

The problem is that you did not have a IOperationFilter setting the corresponding "security" property, there is a big note on the config about that:
https://github.com/heldersepu/csharp-proj/blob/SwaggerBasicAuthDemo/SwaggerBasicAuthDemo/SwaggerDemo/App_Start/SwaggerConfig.cs#L59

I added the needed change on this commit:
https://github.com/heldersepu/csharp-proj/commit/186ce3ce5156888668ef0ae562d49ac1d33d1aad

-

One more thing, double check what you are doing in your ```OnAuthorization``` method, on your condition to Validate username and password you only respond with Unauthorized for the demo:
https://github.com/heldersepu/csharp-proj/blob/SwaggerBasicAuthDemo/SwaggerBasicAuthDemo/SwaggerDemo/Attributes/BasicAuthenticationAttribute.cs#L29

**Comment by heldersepu** [comment]
Once you have the IOperationFilter your actions with the security property will show a lock on the UI:
![2017-09-24 12_26_17-swagger ui](https://user-images.githubusercontent.com/545474/30784647-fbe408ca-a126-11e7-9d29-4d08bfee3c89.png)

**Comment by vhugogarcia** [comment]
Thanks @heldersepu for the help with the issue. I apologize for the huge file I was taking care of my kiddos while doing the sample project so I forgot to remove those folders while zipping.

I will download the sample you provided in a bit and give it a try.

Thanks again.

**Comment by vhugogarcia** [comment]
It worked fantastic! Thank you so much for the help. And it was great you included the Basic Auth demo in the repository for future references. I saw it also has some OAuths Operation Filters.
