### ISSUE TITLE
DocExpansion.List causing lags

### ISSUE THREAD

**Issue by yojagad** [heldersepu/Swagger-Net#29]
I was wondering if there's a way to collapse/hide/disable the "models" being displayed by the generated swagger but still have the rest of the APIs expanded. DocExpansion.List seems to expand the models as well causing terrible lags in the UI. Of course, one solution is to just use DocExpansion.None and have everything collapsed initially but I was wondering if the above is still possible..?

**Comment by heldersepu** [comment]
I see you are reporting 2 things both are [Swagger-UI](https://github.com/swagger-api/swagger-ui/)...
- Lags in UI rendering models, I have not seen this issue do you seen any lags here: http://swashbuckletest.azurewebsites.net/swagger/ui/index
- Option to Collapse the models, that has been requested take a look here: 
https://github.com/swagger-api/swagger-ui/issues/2834

Since these are UI related I will close this issue, if you have more details on the lags please report it on the UI project, thanks

**Comment by heldersepu** [comment]
I just found out there is an option 'defaultModelExpandDepth' that collapses a lot of the models, I'm going to add that and default it to 0, hopefully that improves your issue.

**Comment by heldersepu** [comment]
@yojagad  When you can try the latest:
https://www.nuget.org/packages/Swagger-Net/8.3.4.402

**Comment by kevineger** [comment]
@heldersepu Adding the `defaultModelExpandDepth: 0` definitely improves the performance however, the behaviour of switching between the _Example Value_ and _Model_ view of an API route leaves the model fully collapsed which is undesirable. I imagine more granularity between default model behaviour for APIs vs a Model list would be ideal.
