### ISSUE TITLE
SwaggerUI: random mixed versions

### ISSUE THREAD

**Issue by Wuedmo** [heldersepu/Swagger-Net#83]
Short introduction: I have 4 versions of 7 controller with ~30 methods.  [SwaggerUI](https://saas.esignanywhere.net/Api/swagger/ui/index) (If you have luck, the site is currently corrupted like I describe)
The site is running all day and at any point and randomly the **versions are mixed up**. 
FYI: happening nearly every ~2-4 months. 

Example: _I'm on the V4 of the Api, and see on some controllers just V1 methods._ 

Meanwhile after lots of research we cannot figure out, at which point this is happening. 
Its neither after an update or some other maintaince. 

We currently have **Swagger-Net 8.3.18.1**.

We figured out that after an **iisreset**, the problem disappears for a while.
But this minor solution is really difficult for us, because we cannot iisreset at any time we want. 

Furthermore, the **OpenApi file** is **also corrupted** at this time. 
But the endpoints which are not shown in SwaggerUI, are available at any time, from any REST Client. 

Nice to know, this is happening at 5 complete **different servers** all the time. (not on the same time)

**Comment by heldersepu** [comment]
> happening nearly every ~2-4 months.
You mean once every ~2-4 months? 
start by updating:
yours: 8.3.18.001
latest: 8.3.22.202

> the OpenApi file is also corrupted at this time.
On the json schema for v4:
https://saas.esignanywhere.net/Api/swagger/docs/V4.0
```
{
"swagger": "2.0",
"info": {
"version": "V4.0",
"title": "eSignAnywhere.Api",
"x-swagger-net-version": "8.3.18.001"
},
"host": "saas.esignanywhere.net",
"basePath": "/Api",
"schemes": ["https"],
"paths": {
"/v4.0/authorization": {},
"/v1.0/envelope/create": {},
"/v1.0/envelope/createFromTemplate": {},
"/v1.0/envelope/{envelopeId}/cancel": {},
"/v1.0/envelope/{envelopeId}": {},
```
Are those v1.0 supposed to be there?

**Comment by Wuedmo** [comment]
Yeah once every 2-4 months after a fresh iisreset to solve this issue.  

> what do you mean?
That exactly this V1 should not be there. There should be only V4.

We will update, and I keep you informed if this is happening again in the next months.

**Comment by heldersepu** [comment]
I also have a multi version site for tests:
http://swagger-net-test-multiapiversions.azurewebsites.net/swagger/ui/index
And never encountered any issues.

To get a good troubleshooting going make sure you understand the layers on this...

Swagger-Net generates the json you see here:
https://saas.esignanywhere.net/Api/swagger/docs/V4.0
if that is not correct there could a problem in your code or a bug on Swagger-Net 
get familiar with the OAS 2.0 that is the schema currently in use
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md

If the json is correct but the UI shows something else we have to report it to the Swagger-UI team:
https://github.com/swagger-api/swagger-ui

Since this issue is not something specific that I can fix now I'm going to close it.
Feel free to open a new on with more details
